version: loom-schema/v2
name: Products
using:
  - shop.core.*
table:
  name: products_base
  extension:
    strategy: sidecar_eav
    ext_table: products_ext
fields:
  - name: id
    type: bigint
    required: true
  - name: name
    type:
      ref: string
      args: { max_length: 255 }
    required: true
  - name: base_price
    type: shop.core.Money
primary_key: [ id ]
